cooker_stop:
  target:
    entity:
      integration: tokit_cooker
    device:
      integration: tokit_cooker
  name: Stop cooking
  description: Stop the cooking process.

cooker_start:
  target:
    entity:
      integration: tokit_cooker
    device:
      integration: tokit_cooker
  name: Start cooking
  description: Start the cooking process.
  fields:
    name:
      name: Menu
      required: false
      # Example value that can be passed for this field
      example: "精煮饭"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control
      # the input UI for this field
      selector:
        select:
          options:
            - "精煮饭"
            - "快煮饭"
            - "煮粥"
            - "保温"
            - "蒸煮"
            - "炖汤"
            - "蛋糕"
            - "酸奶"
            - "热饭"
            - "小米粥"
            - "八宝粥"
            - "煲仔饭"
            - "香甜煮"
            - "发芽饭"
    duration:
      name: Duration
      required: false
      example: 60 # min
      selector:
        number:
          min: 5
          max: 1440
    schedule_time:
      name: Schedule Time
      required: false
      example: 480 # 8:00:00
      selector:
        number:
          min: 0
          max: 1440
    auto_keep_warm:
      name: Auto Keep Warm
      required: false
      example: true
      selector:
        boolean:
cooker_set_menu:
  target:
    entity:
      integration: tokit_cooker
    device:
      integration: tokit_cooker
  name: Set Menu
  description: Set the cooker menu.
  fields:
    index:
      name: Index
      required: true
      example: 8
      default: 8
      selector:
        number:
          min: 1
          max: 8
    name:
      name: Menu
      required: true
      # Example value that can be passed for this field
      example: "精煮饭"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control
      # the input UI for this field
      selector:
        select:
          options:
            - "精煮饭"
            - "快煮饭"
            - "煮粥"
            - "保温"
            - "蒸煮"
            - "炖汤"
            - "蛋糕"
            - "酸奶"
            - "热饭"
            - "小米粥"
            - "八宝粥"
            - "煲仔饭"
            - "香甜煮"
            - "发芽饭"
    duration:
      name: Duration
      required: false
      example: 60 # min
      selector:
        number:
          min: 5
          max: 1440
    schedule_time:
      name: Schedule Time
      required: false
      example: 480 # 8:00:00
      selector:
        number:
          min: 0
          max: 1440
    auto_keep_warm:
      name: Auto Keep Warm
      required: false
      example: true
      selector:
        boolean:
cooker_del_menu:
  target:
    entity:
      integration: tokit_cooker
    device:
      integration: tokit_cooker
  name: Delete Menu
  description: Delete the cooker menu.
  fields:
    index:
      name: Index
      required: true
      example: 8
      default: 8
      selector:
        number:
          min: 1
          max: 8